;; DGO definition file for Awful Village level
;; We use the convention of having a longer DGO name for levels without precomputed visibility.

;; the actual file name still needs to be 8.3
("PRE.DGO"
(
 "static-screen.o"
 "blocking-plane.o"
 "wall-plat.o"
 "target-tube.o"
 "jungle-obs.o"
 ;;"dark-eco-pool.o" causes crashing coming from misty straight to here
 "snow-flutflut-obs.o"
 "bonelurker.o"
 "green-eco-lurker.o"
 "battlecontroller.o"
 "preundg-obs.o"
 "tpage-710.go"
 "tpage-842.go"
 "tpage-711.go"
 "tpage-712.go"
 "ambushdoor-ag.go"
 "helix-slide-door-ag.go"
 "swampcam-ag.go"
 "plat-ag.go"
 "green-eco-lurker-ag.go"
 "babak-ag.go"
 "bonelurker-ag.go"
 "mistycam-ag.go"
 "silostep-ag.go"
 "gravityswitch-ag.go"
 "jng-iris-door-ag.go"
 "maindoor-ag.go"
 "snow-switch-ag.go"
 "snow-button-ag.go"
 "orb-cache-top-ag.go"
 "eichar-pole+0-ag.go"
 "eichar-flut+0-ag.go"
 "water-anim-sunken-dark-eco-ag.go"
 "water-anim-sunken-ag.go"
 "eichar-tube+0-ag.go"
 "wall-plat-ag.go"
 "ef-plane-ag.go"
 "flut-saddle-ag.go"
 "flutflut-plat-large-ag.go"
 "flutflut-plat-med-ag.go"
 "flutflut-plat-small-ag.go"
 ;;"tpage-398.go" using snowy tpages for flutflut
 ;;"tpage-400.go"
 ;;"tpage-399.go"
 ;;"tpage-401.go"
 ;;"tpage-1470.go"
 "preundg.go"
 ))