;; DGO definition file for Awful Village level
;; We use the convention of having a longer DGO name for levels without precomputed visibility.

;; the actual file name still needs to be 8.3
("TSZ.DGO"
 (
  "oracle.o"
  "linear-plat.o"
  "village-obs.o"
  "villagep-obs.o"
  "village1-part.o"
  "village1-part2.o"
  "village3-part.o"
  "village3-obs.o"
  ;;"misty-part.o"
  "test-zone-obs.o"
  "lavatube-obs.o"
  "lavatube-part.o"
  "steam-cap.o"
  "sunken-elevator.o"
  "village2-part.o"
  "village2-obs.o"
  "village2-part2.o"
  "fisher.o"
  "sculptor.o"
  ;;"ogre-obs.o"
  "tpage-398.go" 
  "tpage-400.go"
  "tpage-399.go"
  "tpage-401.go"
  "tpage-1470.go"
  "shortcut-boulder-ag.go"
  "muse-ag.go"
  "fisher-ag.go"
  "village2cam-ag.go"  
  "sunken-elevator-ag.go"
  "oracle-ag.go"
  "steam-cap-ag.go"
  "lavayellowtarp-ag.go"
  "plat-ag.go"
  "plat-eco-ag.go"
  "test-actor-ag.go"
  "test-actor2-ag.go"
  "hutlamp-ag.go"
  "test-zone.go"
  )
 )